import autoCompleteFunc from './modules/autoCompleteFunc';
autoCompleteFunc();
import datePicker from './modules/datepicker';
datePicker();
import swiperCard from './modules/swiper-destinations';
swiperCard();
import breakpointsChecker from './modules/swiper-testimonials';
breakpointsChecker();
import scrollAniimation from './modules/scrollAniimation';
scrollAniimation();
import mobileNav from './modules/mobile-nav.js';
mobileNav();
